import asyncio
from typing import Any, Awaitable, Callable, Dict, List, Optional

from loguru import logger
from pipecat.frames.frames import TTSSpeakFrame

from app.core.config import settings
from app.meeting_room.data.crud_interfaces import ResumeRoomCRUD
from app.meeting_room.resume_analysis_pipeline.analysis_orchestrator import FlushRequest
from app.meeting_room.resume_analysis_pipeline.config_jsons_definitions.coverage_schema import (
    ASKABLE_COVERAGE_SCHEMA,
    complete_when_for_target,
)
from app.meeting_room.resume_analysis_pipeline.completeness_status import (
    build_unable_to_answer_patch,
)
from app.meeting_room.resume_analysis_pipeline.next_target import gap_key
from app.meeting_room.resume_analysis_pipeline.question_chain import (
    ANSWER_GRADE_UNABLE_TO_ANSWER,
    TERMINAL_GRADES,
    run_answer_grading_chain,
)

CLOSING_MESSAGE = (
    "That covers everything I wanted to ask -- thank you, and nice work "
    "practicing your resume walkthrough today!"
)


class InterviewDirector:
    """Drives the ENTIRE conversation for the session -- there is no persona
    LLM anywhere; this is the sole source of everything the bot says.

    Two states:
      * idle -- nothing pending. The candidate falling silent for
        `resume_room_silence_hardbound_seconds` triggers `_advance_from_queue`,
        which pops the next already-worded question off `questions.queue`
        (regenerated by the background combined-analysis call -- see
        `resume_analysis_pipeline/analysis_orchestrator.py`/`combined_chain.py`)
        and opens a round for it.
      * awaiting_answer -- a question has been spoken. The candidate's
        speech is buffered here instead of reaching the transcript live.
        Falling silent for `resume_room_answer_silence_seconds` ends the
        answer, handled by `_finish_answer`.

    Target *selection* is entirely the analysis worker's job now, not this
    class's: `questions.queue` is regenerated wholesale every combined-call
    cycle (conflicts/unresolved first, then ordinary coverage gaps, in
    Python-authoritative priority order -- see `next_target.compute_candidate_queue`),
    already fully worded. This class only ever pops the head of that queue
    and speaks it -- no LLM call at pop time, and no in-memory bookkeeping
    of what's been given up on or forced (that now lives on the session row,
    since the analysis worker's task needs to see it too -- `mark_target_given_up`/
    `mark_forced_topic_spent` in `data/crud.py`).

    Every question lives inside a ROUND (`data/crud.py`'s
    `questions.rounds`): one round per subject, holding one or more
    exchanges (the opening question plus any probes) under a per-round
    question budget (`resume_room_max_questions_per_round`). A round closes
    once the narrow per-answer grading call's `answer_grade` is terminal
    (SUFFICIENT / UNABLE_TO_ANSWER) or the budget runs out.

    The opening round is special: it has no single `target`/`complete_when`
    bar (a multi-block opener), so `_finish_answer` skips grading entirely
    for it and goes straight to flush + advance.

    Every other round's answer is graded by ONE narrow LLM call
    (`question_chain.run_answer_grading_chain`) against ONLY that round's
    own `target_complete_when` bar and the conversation history -- it never
    sees the whole resume/coverage rubric or a candidate list, since
    deciding what to ask about NEXT is not its job at all.

    Extraction+coverage-grading+queue-regeneration (the combined analysis
    call) is triggered out-of-turn every answer
    (`orchestrator.flush_transcript(..., wait=...)`) and is entirely off the
    narrow grading call's critical path, but IS awaited (`wait=True`) right
    before `_advance_from_queue` -- the queue must reflect this answer's own
    contribution before the next question is popped from it.

    Questions are spoken straight through TTS (TTSSpeakFrame,
    append_to_context=False). `pipeline.py` additionally suppresses
    broadcasting an `InterruptionFrame` when the candidate starts talking,
    so a question in flight is never cut off mid-utterance -- speaking-state
    detection (UserStartedSpeakingFrame/UserStoppedSpeakingFrame, which the
    silence timers above depend on) is unaffected by that suppression.
    """

    # How many times one answer may be re-graded after a call came back with
    # nothing usable (no terminal grade, no probe), before we give up and
    # move on. One retry covers the transient provider/schema failure this
    # exists for; more would just keep a broken model in a loop while the
    # candidate waits in silence.
    _MAX_REGRADE_ATTEMPTS = 1

    def __init__(
        self,
        session_id: str,
        crud: ResumeRoomCRUD,
        orchestrator,
        worker,
        *,
        on_complete: Optional[Callable[[], Awaitable[None]]] = None,
    ):
        self._session_id = session_id
        self._crud = crud
        self._orchestrator = orchestrator
        self._worker = worker
        # Called once the closing message has been queued for speech --
        # BotSession.end_session() in practice, which queues an EndFrame
        # right behind it so the pipeline (and with it the Daily room, via
        # the usual _on_bot_done/_close_out teardown) shuts down only after
        # that frame has flowed all the way through TTS/output, not before.
        self._on_complete = on_complete

        self._awaiting_answer = False
        self._current_round_id: Optional[str] = None
        # Why the currently-open round exists, when it wasn't picked
        # organically: "conflict:<id>" / "unresolved:<id>", else None.
        # Folded into questions.forced_topics_spent (crud.mark_forced_topic_spent)
        # the moment the round closes.
        self._current_round_forced: Optional[str] = None
        self._current_question_text: Optional[str] = None
        self._buffer: List[str] = []
        self._pending: Optional[asyncio.Task] = None
        self._busy = False
        self._closed = False
        # How many times THIS answer has been re-graded after a grading call
        # came back with nothing usable. Reset every time a question is
        # asked; bounded so a persistently failing call can't loop forever.
        self._regrade_attempts = 0


    async def ask_opening_question(self, question: str) -> None:
        """The fixed, LLM-free kickoff -- spoken exactly as given, no
        wording call. Graded like any other round from here on: the opening
        answer may be probed if it's thin, exactly like an ordinary round
        (a deliberate change from the old hardcoded never-re-probe). No
        `target` -- it's a broad multi-block opener, not about one gap."""
        await self._open_round(question, forced=None, target=None)


    def record_candidate_text(self, text: str) -> None:
        """Buffers a finalized STT chunk for the answer currently in
        progress, so _finish_answer can join the whole thing for grading.
        Purely additive -- pipeline.py's persist() also always sends this
        same text straight to the transcript/extraction queue live, so this
        no longer gates anything the way it used to."""
        if self._awaiting_answer and text.strip():
            self._buffer.append(text.strip())


    def on_speaking_change(self, is_speaking: bool) -> None:
        """Same cancel-on-resume debounce the batched completeness worker
        uses, with the wait and the action both depending on which state
        we're in."""
        if is_speaking:
            if self._pending is not None and not self._pending.done():
                self._pending.cancel()
            return

        if self._busy:
            return
        if self._pending is not None and not self._pending.done():
            return

        self._pending = asyncio.create_task(self._run_after_silence())


    def cancel(self) -> None:
        if self._pending is not None and not self._pending.done():
            self._pending.cancel()


    async def _run_after_silence(self) -> None:
        delay = (
            settings.resume_room_answer_silence_seconds
            if self._awaiting_answer
            else settings.resume_room_silence_hardbound_seconds
        )
        try:
            await asyncio.sleep(delay)
        except asyncio.CancelledError:
            return

        self._busy = True
        try:
            # An ungraded answer for a still-open round takes priority over
            # advancing to a new one even if `_awaiting_answer` somehow got
            # cleared (a cycle that died between clearing it and asking the
            # next question) -- without this a lost turn silently becomes
            # "advance to the next round" with nothing to speak from.
            if self._awaiting_answer or (self._current_round_id is not None and self._buffer):
                await self._finish_answer()
            else:
                await self._advance_from_queue()
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("interview director cycle failed")
        finally:
            self._busy = False


    async def _open_round(
        self,
        question: str,
        *,
        forced: Optional[str],
        target: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Speaks `question` and opens a brand-new round for it -- the
        opening question of a fresh subject, whether picked organically or
        forced (a conflict/unresolved topic that jumped the queue).
        `target` is `{"block", "item_id", "fields"}` describing what the
        question is about (already sanitized/built by the caller), stored on
        the round so a later UNABLE_TO_ANSWER grade can be committed back
        into field_completeness precisely."""
        self._current_question_text = question
        self._buffer = []
        self._awaiting_answer = True
        self._current_round_forced = forced
        self._regrade_attempts = 0

        try:
            await self._worker.queue_frames(
                [TTSSpeakFrame(text=question, append_to_context=False)]
            )
        except Exception:
            logger.exception("failed to speak interview question")

        try:
            self._current_round_id = await asyncio.shield(
                self._crud.start_round(
                    self._session_id,
                    question_text=question,
                    forced_topic=forced,
                    target=target,
                )
            )
        except asyncio.CancelledError:
            pass


    async def _probe_round(self, question: str) -> None:
        """Speaks `question` as one more exchange on the CURRENT round --
        narrowing in on the same subject rather than opening a new one."""
        self._current_question_text = question
        self._buffer = []
        self._awaiting_answer = True
        self._regrade_attempts = 0

        try:
            await self._worker.queue_frames(
                [TTSSpeakFrame(text=question, append_to_context=False)]
            )
        except Exception:
            logger.exception("failed to speak interview question")

        if self._current_round_id is None:
            return
        try:
            await asyncio.shield(
                self._crud.append_round_question(
                    self._session_id, self._current_round_id, question
                )
            )
        except asyncio.CancelledError:
            pass


    @staticmethod
    def _build_conversation_history(row: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Every question asked and answer given so far this session,
        flattened across every round in order, oldest first -- the whole
        conversation, no per-round windowing or truncation. Handed to
        run_answer_grading_chain as `conversation_history`."""
        history: List[Dict[str, Any]] = []
        questions = (row or {}).get("questions") or {}
        rounds = questions.get("rounds") or {}
        for round_id in questions.get("round_order") or []:
            round_row = rounds.get(round_id) or {}
            for exchange in round_row.get("exchanges") or []:
                history.append({
                    "question": exchange.get("question"),
                    "answer": exchange.get("answer"),
                })
        return history


    async def _pop_next_queue_item(self, exclude_key: Optional[str]) -> Optional[Dict[str, Any]]:
        """Pops entries off questions.queue, discarding any whose key matches
        `exclude_key` (the round that's *just now* closing) -- a stale queue
        snapshot popped before this round's own closure has been folded into
        a regeneration cycle can still list this exact target, and asking it
        again immediately after it just closed (SUFFICIENT, UNABLE_TO_ANSWER,
        or given up on being capped) would repeat a question the candidate
        just answered. Discarding here is safe: the item is genuinely stale,
        and the next real regeneration cycle won't reinsert it once the
        server-side state it's excluded from actually reflects this
        closure."""
        while True:
            item = await self._crud.pop_question_queue_head(self._session_id)
            if item is None:
                return None
            if exclude_key is not None and item.get("key") == exclude_key:
                logger.info(
                    "interview director discarding stale queue entry for just-closed "
                    "target {} (session {})", exclude_key, self._session_id,
                )
                continue
            return item


    async def _advance_from_queue(
        self, pending_flush: Optional[FlushRequest] = None, *, exclude_key: Optional[str] = None,
    ) -> None:
        """Pops the next already-worded question off questions.queue and
        opens a round for it -- no LLM call, the combined analysis call
        already worded it.

        `exclude_key` -- see `_pop_next_queue_item` -- is the gap/forced-topic
        key of the round that just closed, if any; a popped entry matching it
        is discarded as stale rather than asked again.

        `pending_flush`, when given, is the in-flight combined-analysis
        batch triggered (fire-and-forget) by this same turn's
        `_finish_answer` -- not awaited yet, so the very first pop attempt
        below reads whatever `questions.queue` already holds, off this
        turn's critical path entirely. Only if that first pop comes back
        empty do we fall back to awaiting `pending_flush` and popping again
        once it lands, since an empty queue is otherwise read as "genuinely
        nothing left to ask" -- and a queue that's merely stale (this turn's
        own contribution hasn't landed yet) must not be mistaken for that.
        Once the retry (or the no-pending-flush case) still comes back
        empty, the interview is genuinely over."""
        item = await self._pop_next_queue_item(exclude_key)
        if item is None and pending_flush is not None:
            try:
                await asyncio.wait_for(
                    pending_flush.done.wait(),
                    timeout=settings.resume_room_flush_timeout_seconds,
                )
            except asyncio.TimeoutError:
                pass
            item = await self._pop_next_queue_item(exclude_key)
        if item is None:
            await self._complete_interview()
            return
        key = item.get("key") or ""
        forced = key if key.startswith(("conflict:", "unresolved:")) else None
        target = {
            "block": item.get("block"),
            "item_id": item.get("item_id"),
            "fields": item.get("fields"),
        }
        await self._open_round(item["question"], forced=forced, target=target)


    async def _finish_answer(self) -> None:
        round_id = self._current_round_id
        answer_text = " ".join(self._buffer).strip()
        if round_id is None or not answer_text:
            return

        # Deliberately STAYS in awaiting_answer until grading has actually
        # returned (or, for the opening round, until we're past the point of
        # no return) -- this whole cycle runs inside the very task
        # `on_speaking_change(True)` cancels when the candidate resumes
        # speaking, so a turn killed mid-grading must leave no trace. The
        # buffer clears here so anything said DURING grading accumulates
        # cleanly on top of nothing; the CancelledError handler below puts
        # both halves back together.
        self._buffer = []
        graded = False

        row = await self._crud.get_session(self._session_id)
        round_row = (
            ((row or {}).get("questions") or {}).get("rounds", {}).get(round_id)
        ) or {}
        current_target = round_row.get("target")

        if current_target is None:
            # The opening round: a broad multi-block opener has no single
            # complete_when bar to grade against, so there is nothing to
            # grade -- go straight to flush + advance, per the agreed design.
            graded = True
            self._awaiting_answer = False
            record_answer_task = asyncio.shield(
                self._crud.record_round_answer(self._session_id, round_id, answer_text)
            )
            close_round_task = asyncio.shield(
                self._crud.close_round(self._session_id, round_id, grade=None)
            )
            self._current_round_id = None
            self._current_round_forced = None

            pending_flush = await self._orchestrator.flush_transcript(self._session_id, wait=False)
            await self._advance_from_queue(pending_flush)

            try:
                await record_answer_task
                await close_round_task
            except asyncio.CancelledError:
                pass
            return

        try:
            history = self._build_conversation_history(row or {})
            target_complete_when = complete_when_for_target(ASKABLE_COVERAGE_SCHEMA, current_target)

            # Fire-and-forget: every line of this answer already reached the
            # combined-analysis queue live as it was transcribed (see
            # pipeline.py's persist()), so there's nothing to lose by forcing
            # that batch out now instead of waiting for the char-count
            # trigger. Never awaited here -- the combined call is entirely
            # off this turn's critical path; it's awaited later, right
            # before _advance_from_queue needs its result.
            await self._orchestrator.flush_transcript(self._session_id, wait=False)

            # The ONE LLM call for this turn: grades this answer against
            # ONLY this round's own target_complete_when bar. Deciding what
            # to ask next is not this call's job at all -- that's the
            # combined analysis call's queue, popped by _advance_from_queue
            # below once it's been re-flushed to reflect this answer.
            result = await run_answer_grading_chain(history, answer_text, target_complete_when)

            # Past this line the turn is ours to commit -- everything below
            # is shielded, and a cancellation can no longer put the answer
            # back for re-grading.
            graded = True
            self._awaiting_answer = False

            if result.get("is_meta_question") and result.get("meta_response"):
                # Deliberately NOT recorded via record_round_answer: a round's
                # exchange is a fixed one-shot {question, answer} slot, unlike
                # the old free-form per-thread message log -- filling it with
                # an off-topic aside would leave no open slot for the REAL
                # answer that follows once the pending question is re-spoken.
                try:
                    await asyncio.shield(
                        self._crud.append_transcript_line(self._session_id, "user_aside", answer_text)
                    )
                    await asyncio.shield(
                        self._crud.append_transcript_line(
                            self._session_id, "assistant_aside", result["meta_response"]
                        )
                    )
                except asyncio.CancelledError:
                    pass
                await self._handle_meta_question(result["meta_response"])
                return

            # Kick off the answer-persistence write now (asyncio.shield starts
            # it running immediately) but don't block on it until AFTER the
            # next question/probe has already been queued for TTS below --
            # this write doesn't affect what gets spoken next, only
            # bookkeeping, so it shouldn't sit on the critical path.
            record_answer_task = asyncio.shield(
                self._crud.record_round_answer(self._session_id, round_id, answer_text)
            )

            grade = result.get("answer_grade")
            llm_usage = result.get("_llm_usage")
            probe_question = result.get("probe_question")
            terminal = grade in TERMINAL_GRADES

            # round_row (computed above, before this turn's answer was
            # recorded) is still accurate here -- record_round_answer only
            # fills in an existing exchange's `answer` field (crud.py), it
            # never changes the exchange count, and nothing else touches
            # questions.rounds concurrently.
            budget = int(
                round_row.get("max_questions") or settings.resume_room_max_questions_per_round
            )
            spent = len(round_row.get("exchanges") or [])
            capped = spent >= budget

            # These two writes both change what the VERY NEXT candidate-queue
            # computation (triggered by the flush below) will see -- a
            # just-given-up target's exclusion, and a just-forced topic's
            # "spent" mark -- so they're awaited HERE, before the flush,
            # rather than deferred like record_answer_task/close_round_task.
            # Deferring them (as bookkeeping-only writes are elsewhere in
            # this method) would race the flush-triggered combined call,
            # which could regenerate the queue before either write lands and
            # hand the same target/topic straight back out again -- exactly
            # what this bookkeeping exists to prevent.
            if capped and not terminal:
                logger.info(
                    "interview director giving up on round {} after {} of {} questions",
                    round_id, spent, budget,
                )
                if current_target:
                    await asyncio.shield(
                        self._crud.mark_target_given_up(
                            self._session_id, current_target.get("block"), current_target.get("item_id"),
                        )
                    )

            if not terminal and not capped and probe_question:
                await self._probe_round(probe_question)
                try:
                    await record_answer_task
                except asyncio.CancelledError:
                    pass
                return

            if not terminal and not capped:
                # No probe at all -- a fail-soft `_empty_result` after a
                # provider/schema error, or a response that ignored the
                # instruction to always draft one. That is a failed grading
                # round, not a finished turn -- put the answer back and
                # re-grade it on the next silence rather than closing the
                # round on nothing. Bounded, so a call that keeps failing
                # can't loop: after `_MAX_REGRADE_ATTEMPTS` we move on with
                # whatever grade the last response did give us.
                self._regrade_attempts += 1
                if self._regrade_attempts <= self._MAX_REGRADE_ATTEMPTS:
                    logger.warning(
                        "grading round {} produced no probe and no terminal verdict "
                        "(attempt {}) -- restoring the turn to re-grade on the next silence",
                        round_id, self._regrade_attempts,
                    )
                    self._awaiting_answer = True
                    self._buffer = [answer_text] + self._buffer
                    try:
                        await record_answer_task
                    except asyncio.CancelledError:
                        pass
                    return
                logger.warning(
                    "grading round {} produced nothing usable {} times -- moving on",
                    round_id, self._regrade_attempts,
                )

            if self._current_round_forced:
                await asyncio.shield(
                    self._crud.mark_forced_topic_spent(self._session_id, self._current_round_forced)
                )

            # Same deferral as record_answer_task above: start this write
            # now, but don't wait on it until after _advance_from_queue below
            # has already queued the next question's TTS frame.
            close_round_task = asyncio.shield(
                self._crud.close_round(
                    self._session_id, round_id, grade=grade, llm_usage=llm_usage,
                )
            )

            if grade == ANSWER_GRADE_UNABLE_TO_ANSWER:
                # The one verdict the combined analysis call can never infer
                # on its own (a decline leaves no resume_data value for it to
                # ever judge) -- commit it now, precisely, using the round's
                # own stored target. Awaited (not deferred) for the same
                # queue-freshness reason as mark_target_given_up/
                # mark_forced_topic_spent above: it flips this field's
                # terminal status, which the very next candidate-queue
                # computation must already see.
                closing_target = (round_row or {}).get("target")
                if closing_target:
                    patch = build_unable_to_answer_patch(
                        (row or {}).get("field_completeness") or {}, closing_target
                    )
                    if patch:
                        try:
                            await asyncio.shield(
                                self._crud.apply_field_completeness(self._session_id, patch)
                            )
                        except asyncio.CancelledError:
                            pass

            # This round's own candidate key (whichever way it was picked) --
            # a stale queue snapshot popped below may still list it, since
            # this round's closure hasn't necessarily been folded into a
            # regeneration cycle yet. See _pop_next_queue_item.
            closing_key = self._current_round_forced or gap_key(
                current_target.get("block"), current_target.get("item_id")
            )

            self._current_round_id = None
            self._current_round_forced = None

            pending_flush = await self._orchestrator.flush_transcript(self._session_id, wait=False)
            await self._advance_from_queue(pending_flush, exclude_key=closing_key)

            try:
                await record_answer_task
                await close_round_task
            except asyncio.CancelledError:
                pass
        except asyncio.CancelledError:
            if not graded:
                # The candidate resumed speaking while we were grading, so
                # this was never end-of-turn. Put the turn back exactly as
                # we found it -- the answer, plus whatever they added while
                # the call was in flight -- so the next silence re-grades
                # the whole thing through the same narrow call.
                self._awaiting_answer = True
                self._buffer = [answer_text] + self._buffer
                logger.info(
                    "answer grading for round {} cancelled mid-flight -- turn restored, "
                    "will re-grade on the next silence",
                    round_id,
                )
            raise


    async def _handle_meta_question(self, response_text: str) -> None:
        """The candidate went off-script to ask about the process rather than
        answer. Speak the answer, then re-speak the exact pending question
        (cached in _current_question_text when it was first asked) and wait
        again -- no grade, no probe spent, no round write at all."""
        self._awaiting_answer = True
        self._buffer = []
        try:
            await self._worker.queue_frames([
                TTSSpeakFrame(text=response_text, append_to_context=False),
                TTSSpeakFrame(text=self._current_question_text, append_to_context=False),
            ])
        except Exception:
            logger.exception("failed to speak meta-question response")


    async def _complete_interview(self) -> None:
        """Nothing is left to ask -- genuinely done. The only remaining
        caller of _leave_interview_mode: a transient LLM failure must never
        reach here, which is why _finish_answer's "no probe, not terminal,
        not capped" branch re-grades the answer instead of dropping out of
        interview mode. Speaks the closing line exactly once, even if
        further silences keep re-triggering an empty round-advance, then
        ends the session.

        Ending is queued as a *separate* frame right behind the closing
        TTSSpeakFrame rather than fired off immediately: pipecat processes
        queued frames through the pipeline in order, so an EndFrame queued
        here only reaches (and tears down) the transport after the closing
        message has actually been synthesized and played, not before. The
        rest of teardown (marking the CRUD session finished, deleting the
        Daily room, running the final resolution pass) is the same
        `_on_bot_done`/`_close_out` path every other session end already
        goes through -- see room-orchestration.md -- there is nothing
        closing-specific to duplicate here.
        """
        self._leave_interview_mode()
        if self._closed:
            return
        self._closed = True
        try:
            await self._worker.queue_frames(
                [TTSSpeakFrame(text=CLOSING_MESSAGE, append_to_context=False)]
            )
        except Exception:
            logger.exception("failed to speak closing message")

        if self._on_complete is not None:
            try:
                await self._on_complete()
            except Exception:
                logger.exception("failed to end session after closing message")


    def _leave_interview_mode(self) -> None:
        self._awaiting_answer = False
        self._current_round_id = None
        self._current_round_forced = None
        self._current_question_text = None
        self._buffer = []
